webtalk_init -webtalk_dir E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.sim/sim_1/behav/xsim/xsim.dir/tb_Top_module_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 25 21:23:20 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "034257ed-7387-4d76-9d11-c50f1c7d45b3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4662d9107aa040f2848c4bf267d3122d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "305" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 5900HX with Radeon Graphics        " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3294 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "11 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "5" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7468_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3133287646 -regid "" -xml E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.sim/sim_1/behav/xsim/xsim.dir/tb_Top_module_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.sim/sim_1/behav/xsim/xsim.dir/tb_Top_module_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.sim/sim_1/behav/xsim/xsim.dir/tb_Top_module_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
