# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7s50ftgb196-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.cache/wt} [current_project]
set_property parent.project_path {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo {e:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/I2C/I2C/I2C.srcs/sources_1/new/I2C.vhd}
  {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/SPI_SDIO/spi_sdio/SPI_SDIO.vhd}
  {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.srcs/sources_1/new/controller.vhd}
  {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/spi_protocol/spi_data.vhd}
  {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/spi_protocol/spi_protocol.vhd}
  {E:/MSc.Iran university of science and technology/Term 1/VHDL/Project/controller/CTRL/CTRL.srcs/sources_1/new/Top_module.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top Top_module -part xc7s50ftgb196-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_module_utilization_synth.rpt -pb Top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
